"""Render an audit report as a single self-contained HTML file.

JSON stays the canonical output (per the spec); this is the human-facing view for a demo:
one file, inline CSS only, no external assets, an SVG score gauge, severity-coded and
collapsible findings. Everything is HTML-escaped.
"""
from __future__ import annotations

import html
from typing import Any, Dict, List

_SEV_COLOR = {
    "critical": "#b00020", "high": "#d84315", "medium": "#e6a100",
    "low": "#4a7", "info": "#789",
}
_GRADE_COLOR = {"A": "#2e7d32", "B": "#66bb6a", "C": "#e6a100", "D": "#ef6c00", "F": "#b00020"}


def render_html(report: Dict[str, Any]) -> str:
    """Return a complete HTML document string for *report*."""
    site = html.escape(str(report.get("site", "")))
    score = report.get("score", {})
    value = score.get("value", 0)
    grade = score.get("grade", "F")
    disc = score.get("discoverability", 0)
    eng = score.get("engagement", 0)
    summary = report.get("summary", {})
    findings = report.get("findings", [])

    return f"""<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>AI Readiness Audit — {site}</title>
<style>{_CSS}</style></head>
<body>
<header class="hero">
  <div class="gauge">{_gauge_svg(value, grade)}</div>
  <div class="hero-meta">
    <div class="eyebrow">AI Visibility Score</div>
    <h1>{site}</h1>
    <div class="subscores">
      {_subscore("Discoverability", disc)}
      {_subscore("Engagement", eng)}
    </div>
    <div class="meta-line">Audited {html.escape(str(report.get('audited_at','')))} ·
      profile: {html.escape(str(report.get('profile','balanced')))} ·
      {report.get('pages_crawled',0)} page(s) crawled</div>
    {_comparison_badge(report.get('comparison'))}
  </div>
</header>

<section class="tiles">
  {_tile("Findings", summary.get("total_findings", 0))}
  {_tile("Critical", summary.get("critical", 0), "critical")}
  {_tile("High", summary.get("high", 0), "high")}
  {_tile("Medium", summary.get("medium", 0), "medium")}
  {_tile("Low", summary.get("low", 0), "low")}
</section>

<main>
  <h2>Findings <span class="hint">(most actionable first)</span></h2>
  {_findings_html(findings)}
</main>

<footer>
  <p>Generated by brand-ai-readiness-audit · recommend-only, read-only static audit.
  JSON remains the canonical machine-readable output.</p>
</footer>
</body></html>"""


def _comparison_badge(cmp: Any) -> str:
    """Render the score-vs-previous delta badge, if history comparison is present."""
    if not cmp or cmp.get("delta") is None:
        return ""
    delta = cmp["delta"]
    arrow = "▲" if delta > 0 else ("▼" if delta < 0 else "=")
    color = "#2e7d32" if delta > 0 else ("#b00020" if delta < 0 else "#789")
    return (f'<div class="delta" style="color:{color}">{arrow} {delta:+d} vs previous '
            f'({html.escape(str(cmp.get("previous_score")))} on '
            f'{html.escape(str(cmp.get("previous_at","")))[:10]})</div>')


def _gauge_svg(value: int, grade: str) -> str:
    """An SVG donut gauge showing the overall score and grade."""
    color = _GRADE_COLOR.get(grade, "#b00020")
    r = 52
    circ = 2 * 3.14159 * r
    frac = max(0, min(100, value)) / 100.0
    dash = circ * frac
    return f"""<svg viewBox="0 0 130 130" width="130" height="130" role="img" aria-label="Score {value} of 100">
  <circle cx="65" cy="65" r="{r}" fill="none" stroke="#e6e6e6" stroke-width="12"/>
  <circle cx="65" cy="65" r="{r}" fill="none" stroke="{color}" stroke-width="12"
    stroke-linecap="round" stroke-dasharray="{dash:.1f} {circ:.1f}"
    transform="rotate(-90 65 65)"/>
  <text x="65" y="60" text-anchor="middle" font-size="30" font-weight="700" fill="{color}">{value}</text>
  <text x="65" y="84" text-anchor="middle" font-size="15" fill="#666">grade {html.escape(grade)}</text>
</svg>"""


def _subscore(label: str, value: float) -> str:
    """A labelled horizontal bar for a per-dimension sub-score."""
    pct = max(0, min(100, value))
    return f"""<div class="subscore"><span>{html.escape(label)}</span>
      <div class="bar"><i style="width:{pct}%"></i></div><b>{value}</b></div>"""


def _tile(label: str, count: Any, sev: str = "") -> str:
    """A summary count tile, optionally severity-colored."""
    color = _SEV_COLOR.get(sev, "#334")
    return f"""<div class="tile"><div class="tile-n" style="color:{color}">{html.escape(str(count))}</div>
      <div class="tile-l">{html.escape(label)}</div></div>"""


def _findings_html(findings: List[Dict[str, Any]]) -> str:
    """Render each finding as a collapsible <details> block."""
    if not findings:
        return '<p class="empty">No findings — the site is in good shape on the checks run.</p>'
    out = []
    for f in findings:
        sev = f.get("severity", "medium")
        color = _SEV_COLOR.get(sev, "#789")
        action = f.get("suggested_action", {})
        pages = f.get("affected_pages", []) or []
        pages_html = ""
        if pages:
            items = "".join(f"<li>{html.escape(str(u))}</li>" for u in pages[:10])
            pages_html = f'<div class="pages"><span>Affected pages</span><ul>{items}</ul></div>'
        out.append(f"""<details class="finding">
  <summary>
    <span class="chip" style="background:{color}">{html.escape(sev.upper())}</span>
    <span class="dim">{html.escape(f.get('dimension',''))}</span>
    <span class="ftitle">{html.escape(str(f.get('title','')))}</span>
    <span class="impact" title="impact 1–5">impact {f.get('impact','')}</span>
  </summary>
  <div class="body">
    <p class="why"><b>Why it hurts:</b> {html.escape(str(f.get('why','')))}</p>
    <p class="evidence"><b>Evidence:</b> {html.escape(str(f.get('evidence','')))}</p>
    <p class="fix"><b>Fix ({html.escape(str(action.get('priority','')))}):</b>
       {html.escape(str(action.get('summary','')))}</p>
    {pages_html}
    <p class="cat">category: {html.escape(str(f.get('category','')))} ·
       confidence: {html.escape(str(f.get('confidence','')))} · id: {html.escape(str(f.get('id','')))}</p>
  </div>
</details>""")
    return "\n".join(out)


_CSS = """
* { box-sizing: border-box; }
body { margin:0; font:15px/1.5 -apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;
  color:#1a1a1a; background:#f6f7f9; }
.hero { display:flex; gap:24px; align-items:center; padding:28px 32px; background:#fff;
  border-bottom:1px solid #e6e6e6; flex-wrap:wrap; }
.hero-meta h1 { margin:2px 0 10px; font-size:24px; word-break:break-all; }
.eyebrow { text-transform:uppercase; letter-spacing:.08em; font-size:12px; color:#888; }
.subscores { display:flex; gap:20px; flex-wrap:wrap; margin-bottom:8px; }
.subscore { display:flex; align-items:center; gap:8px; font-size:13px; color:#555; }
.subscore .bar { width:140px; height:8px; background:#eee; border-radius:5px; overflow:hidden; }
.subscore .bar i { display:block; height:100%; background:#4a7; }
.subscore b { color:#222; }
.meta-line { font-size:12px; color:#888; }
.tiles { display:flex; gap:14px; padding:20px 32px; flex-wrap:wrap; }
.tile { background:#fff; border:1px solid #e6e6e6; border-radius:10px; padding:14px 20px;
  min-width:96px; text-align:center; }
.tile-n { font-size:26px; font-weight:700; }
.tile-l { font-size:12px; color:#888; text-transform:uppercase; letter-spacing:.05em; }
main { padding:8px 32px 40px; }
h2 { font-size:18px; } .hint { font-weight:400; color:#999; font-size:13px; }
.finding { background:#fff; border:1px solid #e6e6e6; border-radius:10px; margin:10px 0; }
.finding summary { cursor:pointer; padding:14px 16px; display:flex; gap:10px; align-items:center;
  list-style:none; }
.finding summary::-webkit-details-marker { display:none; }
.chip { color:#fff; font-size:11px; font-weight:700; padding:3px 8px; border-radius:20px; }
.dim { font-size:11px; color:#777; text-transform:uppercase; letter-spacing:.04em; }
.ftitle { font-weight:600; flex:1; }
.impact { font-size:12px; color:#999; }
.finding .body { padding:0 16px 16px; border-top:1px solid #f0f0f0; }
.finding .body p { margin:10px 0; }
.why { color:#333; } .evidence { color:#444; }
.fix { background:#f2f8f4; border-left:3px solid #4a7; padding:8px 12px; border-radius:4px; }
.pages span { font-size:12px; color:#888; } .pages ul { margin:4px 0; padding-left:18px; font-size:13px; color:#556; }
.cat { font-size:11px; color:#aaa; }
.empty { color:#4a7; font-weight:600; }
footer { padding:20px 32px; color:#999; font-size:12px; border-top:1px solid #e6e6e6; background:#fff; }
"""
